linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert

run:
  skips-files:
    - ".*\\_test\\.go$"

linters-settings:
  stylecheck:
    go: "1.21"
    checks:
      - all
      - ST1*
  gosec:
    excludes:
      - G204
      - G302
  errcheck:
    check-type-assertions: false
    check-blank: false
    ignore: fmt:.*,Close()$
    disable-default-exclusions: false
    exclude-functions:
      - os.Remove
      - (*os.File).Close()

issues:
  exclude-use-default: false

output:
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: false

  # print linter name in the end of issue text, default is true
  print-linter-name: true